name: All Checks passed
on:
  merge_group:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        edited,
        labeled,
        milestoned,
      ]
  workflow_run:
    workflows: ["PR Integration"]
    types:
      - completed
      - requested

jobs:
  all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@e227a928f31104771f3ec300bb0e21191ed93f17
        with:
          delay: '0'
          retries: '30'
          polling_interval: '1'
